public class Conflicts {

    private String status;
    private String Attalius; 
    private String Fractus;
    private String launchTime;
    private String Spartacus; 
    
    public static String setStatus() {
        // Commentaire sans ligne en plus

        return 'ready';
    }
    
    public String getLaunchTime() {
        return 'Midnight to noon';
    }
    


    public String getLaunchPad() {
        return 'JFK';
    }
    public String getHealthCheck() {
        return 'Perfect';
    }



    public String setLaunchPad2() {
        return 'LaunchPad2';
    }
    public String getHealthCheck2() {
        return 'HealthCheck2';
    }
    public String getAttalius() {
        return 'Attalius';
    }
    public String getHealthCheck23() {
        return 'Attalius';
    }
    public String getHealthCheck24() {
        return 'Attalius24';
    }
}